spring.application.name=eureka-sd
server.port=5050

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:5050/eureka}