CREATE TABLE TB_AREA_MARITIMA (
                                  ID_AREA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  NOME VARCHAR2(100) NOT NULL,
                                  DESCRICAO VARCHAR2(255),
                                  LOCALIZACAO VARCHAR2(255) NOT NULL,
                                  NIVEL_POLUICAO VARCHAR2(50) NOT NULL,
                                  DATA_CADASTRO DATE DEFAULT SYSDATE NOT NULL
)
    /

CREATE TABLE TB_OPERACAO (
                             ID_OPERACAO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             TITULO VARCHAR2(100) NOT NULL,
                             DESCRICAO VARCHAR2(255),
                             DATA_OPERACAO DATE NOT NULL,
                             STATUS VARCHAR2(50) NOT NULL,
                             ID_AREA NUMBER NOT NULL,
                             CONSTRAINT FK_OPERACAO_AREA FOREIGN KEY (ID_AREA) REFERENCES TB_AREA_MARITIMA(ID_AREA)
)
    /