spring.application.name=voluntarios-ms
server.port=0

# ORACLE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SHOW_SQL:false}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Cria uma tabela de historico separado
spring.flyway.table=flyway_schema_history_voluntarios

spring.flyway.baselineOnMigrate=true


# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:5050/eureka}
eureka.instance.instance-id=${spring.application.name}:${random.int}


# Credenciais da API (Basic Auth)
api.security.username=${API_USER}
api.security.password=${API_PASSWORD}
